### ISSUE TITLE
v1.0.0-beta roadmap

### ISSUE THREAD

**Issue by Muhammed-Rahif** [Muhammed-Rahif/quran#2]
- [x] Home surah icons on list item trailing
 - [x] Surah header and bismi separations
 - [x] Compress home list item leading image
 - [ ] Home Juz tab (bookmark tab will not include in this release)
 - [ ] Home search
 - [ ] Settings with dark, white modes (home more button)
 - [ ] Go to page (home more button)
 - [ ] Loading indicator for each Quran page to load the font and the content
 - [ ] Clear cache option in settings
 - [ ] Performance improvements and code refactoring

**Comment by Muhammed-Rahif** [comment]
- [ ] Update package dio cache interceptor isar store to support isar web support
